name: Publish to Comfy registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "pyproject.toml"

permissions:
  issues: write

jobs:
  quality:
    uses: ./.github/workflows/ci.yml

  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      contents: read
    if: ${{ github.repository_owner == 'MajoorWaldi' }}
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@v1
        with:
          ## Add your own personal access token to your Github Repository secrets and reference it here.
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
